### ISSUE TITLE
ImportError: No module named management.commands.django_clear_tables in Django 1.10.8

### ISSUE THREAD

**Issue by heppstux** [defgsus/django-clear-tables#1]
ImportError: No module named management.commands.django_clear_tables

**Comment by defgsus** [comment]
Thanks heppstux, 
i could recreate the issue with
```bash
virtualenv -p python2 env
source env/bin/activate
pip install django==1.10.8
django-admin startproject someproject
cd someproject
<add 'django_clear_tables' to INSTALLED_APPS in someproject/settings.py>
./manage.py django_clear_tables
```
will look into it..

**Comment by defgsus** [comment]
Should be working now (in v0.1.2)
The issue was a missing package in setup.py
(Although managements.commands was exported, management itself wasn't, so the __init__.py was not exported and this won't work in python 2)
